yaml
name: Create Instance

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      # Buat file private key dari GitHub Secret
      - name: Create OCI Private Key File
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > oci_api_key.pem
          chmod 600 oci_api_key.pem

      # Optional debug
      - name: Debug Files
        run: ls -lah

      - name: Run Script
        run: php index.php
        env:
          COMPOSER_PROCESS_TIMEOUT: 0
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_NO_AUDIT: 1

          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}

          # PENTING
          OCI_PRIVATE_KEY_FILENAME: oci_api_key.pem

          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}

          OCI_SHAPE: ${{ secrets.OCI_SHAPE }}
          OCI_OCPUS: ${{ secrets.OCI_OCPUS }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_MEMORY_IN_GBS }}
          OCI_MAX_INSTANCES: ${{ secrets.OCI_MAX_INSTANCES }}

          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}

          # Optional Telegram
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
